name: Test copy release
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: test wrokflow
    steps:
      - uses: actions/checkout@v2
      - name: create release body
        run: |
          cat <<EOF > /tmp/release_body.txt 
          Relese v0.1.0
          initial
          EOF
      - name: run action
        id: test
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          name: v0.1.0
          body-path: /tmp/release_body.txt
          draft: true
